name: Release & Publish to NPM
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set pnpm Version
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Initialise the NPM config
        run: npm config set //registry.npmjs.org:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Run release
        run: npm run release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
