name: Release & Publish to NPM
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: action/checkout@v2
      - name: Install the dependancies
        run: npm ci
      - name: End
        run: echo 'All done!'
