name: Docs

on:
  release:
    types: [published]
  workflow_run:
    workflows: ['Publish']
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: echo "hello world"
